ALTER TABLE CONFIG ADD selPre TEXT;
ALTER TABLE CONFIG ADD selPost TEXT;
UPDATE CONFIG SET selPre='', selPost='';

ALTER TABLE LOGS DROP FOREIGN KEY fk_logs_level;
DROP TABLE LOGS;
DROP TABLE LOGS_LEVEL;

UPDATE CONFIG set version = '9.0';

