const db = require('../db');
const fonctionsMetiers = require('../helpers/fonctionsMetiers');
const fonctionsDelete = require('../helpers/fonctionsDelete');
const logger = require('../winstonLogger');

exports.getProfils = async (req, res, next)=>{
    try {
        let result = await db.query(`
            SELECT
                *,
                idProfil as value,
                libelleProfil as label
            FROM
                PROFILS
        `);

        res.send(result);
    } catch (error) {
        logger.error(error);
        res.sendStatus(500);
    }
}

exports.getOneProfil = async (req, res, next)=>{
    try {
        let result = await db.query(`
            SELECT
                *
            FROM
                PROFILS
            WHERE
                v.idProfil = :idProfil
        `,
        {
            idProfil : req.body.idProfil
        });

        res.send(result);
    } catch (error) {
        logger.error(error);
        res.sendStatus(500);
    }
}

exports.addProfil = async (req, res)=>{
    try {
        let results = await db.query(
            `INSERT INTO
                PROFILS
            SET
                libelleProfil                             = :libelleProfil,
                LDAP_BINDDN                               = :LDAP_BINDDN,
                descriptifProfil                          = :descriptifProfil,
                connexion_connexion                       = :connexion_connexion,
                annuaire_lecture                          = :annuaire_lecture,
                annuaire_ajout                            = :annuaire_ajout,
                annuaire_modification                     = :annuaire_modification,
                annuaire_mdp                              = :annuaire_mdp,
                annuaire_suppression                      = :annuaire_suppression,
                profils_lecture                           = :profils_lecture,
                profils_ajout                             = :profils_ajout,
                profils_modification                      = :profils_modification,
                profils_suppression                       = :profils_suppression,
                categories_lecture                        = :categories_lecture,
                categories_ajout                          = :categories_ajout,
                categories_modification                   = :categories_modification,
                categories_suppression                    = :categories_suppression,
                fournisseurs_lecture                      = :fournisseurs_lecture,
                fournisseurs_ajout                        = :fournisseurs_ajout,
                fournisseurs_modification                 = :fournisseurs_modification,
                fournisseurs_suppression                  = :fournisseurs_suppression,
                typesLots_lecture                         = :typesLots_lecture,
                typesLots_ajout                           = :typesLots_ajout,
                typesLots_modification                    = :typesLots_modification,
                typesLots_suppression                     = :typesLots_suppression,
                lieux_lecture                             = :lieux_lecture,
                lieux_ajout                               = :lieux_ajout,
                lieux_modification                        = :lieux_modification,
                lieux_suppression                         = :lieux_suppression,
                lots_lecture                              = :lots_lecture,
                lots_ajout                                = :lots_ajout,
                lots_modification                         = :lots_modification,
                lots_suppression                          = :lots_suppression,
                sac_lecture                               = :sac_lecture,
                sac_ajout                                 = :sac_ajout,
                sac_modification                          = :sac_modification,
                sac_suppression                           = :sac_suppression,
                catalogue_lecture                         = :catalogue_lecture,
                catalogue_ajout                           = :catalogue_ajout,
                catalogue_modification                    = :catalogue_modification,
                catalogue_suppression                     = :catalogue_suppression,
                materiel_lecture                          = :materiel_lecture,
                materiel_ajout                            = :materiel_ajout,
                materiel_modification                     = :materiel_modification,
                materiel_suppression                      = :materiel_suppression,
                messages_ajout                            = :messages_ajout,
                messages_suppression                      = :messages_suppression,
                verrouIP                                  = :verrouIP,
                commande_lecture                          = :commande_lecture,
                commande_ajout                            = :commande_ajout,
                commande_etreEnCharge                     = :commande_etreEnCharge,
                commande_abandonner                       = :commande_abandonner,
                cout_lecture                              = :cout_lecture,
                cout_ajout                                = :cout_ajout,
                cout_etreEnCharge                         = :cout_etreEnCharge,
                cout_supprimer                            = :cout_supprimer,
                appli_conf                                = :appli_conf,
                reserve_lecture                           = :reserve_lecture,
                reserve_ajout                             = :reserve_ajout,
                reserve_modification                      = :reserve_modification,
                reserve_suppression                       = :reserve_suppression,
                reserve_cmdVersReserve                    = :reserve_cmdVersReserve,
                reserve_ReserveVersLot                    = :reserve_ReserveVersLot,
                vhf_canal_lecture                         = :vhf_canal_lecture,
                vhf_canal_ajout                           = :vhf_canal_ajout,
                vhf_canal_modification                    = :vhf_canal_modification,
                vhf_canal_suppression                     = :vhf_canal_suppression,
                vhf_plan_lecture                          = :vhf_plan_lecture,
                vhf_plan_ajout                            = :vhf_plan_ajout,
                vhf_plan_modification                     = :vhf_plan_modification,
                vhf_plan_suppression                      = :vhf_plan_suppression,
                vhf_equipement_lecture                    = :vhf_equipement_lecture,
                vhf_equipement_ajout                      = :vhf_equipement_ajout,
                vhf_equipement_modification               = :vhf_equipement_modification,
                vhf_equipement_suppression                = :vhf_equipement_suppression,
                vehicules_lecture                         = :vehicules_lecture,
                vehicules_ajout                           = :vehicules_ajout,
                vehicules_modification                    = :vehicules_modification,
                vehicules_suppression                     = :vehicules_suppression,
                vehicules_types_lecture                   = :vehicules_types_lecture,
                vehicules_types_ajout                     = :vehicules_types_ajout,
                vehicules_types_modification              = :vehicules_types_modification,
                vehicules_types_suppression               = :vehicules_types_suppression,
                maintenance                               = :maintenance,
                todolist_perso                            = :todolist_perso,
                todolist_lecture                          = :todolist_lecture,
                todolist_modification                     = :todolist_modification,
                contactMailGroupe                         = :contactMailGroupe,
                tenues_lecture                            = :tenues_lecture,
                tenues_ajout                              = :tenues_ajout,
                tenues_modification                       = :tenues_modification,
                tenues_suppression                        = :tenues_suppression,
                tenuesCatalogue_lecture                   = :tenuesCatalogue_lecture,
                tenuesCatalogue_ajout                     = :tenuesCatalogue_ajout,
                tenuesCatalogue_modification              = :tenuesCatalogue_modification,
                tenuesCatalogue_suppression               = :tenuesCatalogue_suppression,
                cautions_lecture                          = :cautions_lecture,
                cautions_ajout                            = :cautions_ajout,
                cautions_modification                     = :cautions_modification,
                cautions_suppression                      = :cautions_suppression,
                etats_lecture                             = :etats_lecture,
                etats_ajout                               = :etats_ajout,
                etats_modification                        = :etats_modification,
                etats_suppression                         = :etats_suppression,
                notifications                             = :notifications,
                actionsMassives                           = :actionsMassives,
                delegation                                = :delegation,
                commande_valider_delegate                 = :commande_valider_delegate,
                desinfections_lecture                     = :desinfections_lecture,
                desinfections_ajout                       = :desinfections_ajout,
                desinfections_modification                = :desinfections_modification,
                desinfections_suppression                 = :desinfections_suppression,
                typesDesinfections_lecture                = :typesDesinfections_lecture,
                typesDesinfections_ajout                  = :typesDesinfections_ajout,
                typesDesinfections_modification           = :typesDesinfections_modification,
                typesDesinfections_suppression            = :typesDesinfections_suppression,
                carburants_lecture                        = :carburants_lecture,
                carburants_ajout                          = :carburants_ajout,
                carburants_modification                   = :carburants_modification,
                carburants_suppression                    = :carburants_suppression,
                vehiculeHealthType_lecture                = :vehiculeHealthType_lecture,
                vehiculeHealthType_ajout                  = :vehiculeHealthType_ajout,
                vehiculeHealthType_modification           = :vehiculeHealthType_modification,
                vehiculeHealthType_suppression            = :vehiculeHealthType_suppression,
                vehiculeHealth_lecture                    = :vehiculeHealth_lecture,
                vehiculeHealth_ajout                      = :vehiculeHealth_ajout,
                vehiculeHealth_modification               = :vehiculeHealth_modification,
                vehiculeHealth_suppression                = :vehiculeHealth_suppression,
                alertesBenevolesLots_lecture              = :alertesBenevolesLots_lecture,
                alertesBenevolesLots_affectation          = :alertesBenevolesLots_affectation,
                alertesBenevolesLots_affectationTier      = :alertesBenevolesLots_affectationTier,
                alertesBenevolesVehicules_lecture         = :alertesBenevolesVehicules_lecture,
                alertesBenevolesVehicules_affectation     = :alertesBenevolesVehicules_affectation,
                alertesBenevolesVehicules_affectationTier = :alertesBenevolesVehicules_affectationTier,
                codeBarre_lecture                         = :codeBarre_lecture,
                codeBarre_ajout                           = :codeBarre_ajout,
                codeBarre_modification                    = :codeBarre_modification,
                codeBarre_suppression                     = :codeBarre_suppression,
                consommationLots_lecture                  = :consommationLots_lecture,
                consommationLots_affectation              = :consommationLots_affectation,
                consommationLots_supression               = :consommationLots_supression
            ;`,
        {
            libelleProfil                            : req.body.libelleProfil || null,
            LDAP_BINDDN                              : req.body.LDAP_BINDDN || null,
            descriptifProfil                         : req.body.descriptifProfil || null,
            connexion_connexion                      : req.body.connexion_connexion || false,
            annuaire_lecture                         : req.body.annuaire_lecture || false,
            annuaire_ajout                           : req.body.annuaire_ajout || false,
            annuaire_modification                    : req.body.annuaire_modification || false,
            annuaire_mdp                             : req.body.annuaire_mdp || false,
            annuaire_suppression                     : req.body.annuaire_suppression || false,
            profils_lecture                          : req.body.profils_lecture || false,
            profils_ajout                            : req.body.profils_ajout || false,
            profils_modification                     : req.body.profils_modification || false,
            profils_suppression                      : req.body.profils_suppression || false,
            categories_lecture                       : req.body.categories_lecture || false,
            categories_ajout                         : req.body.categories_ajout || false,
            categories_modification                  : req.body.categories_modification || false,
            categories_suppression                   : req.body.categories_suppression || false,
            fournisseurs_lecture                     : req.body.fournisseurs_lecture || false,
            fournisseurs_ajout                       : req.body.fournisseurs_ajout || false,
            fournisseurs_modification                : req.body.fournisseurs_modification || false,
            fournisseurs_suppression                 : req.body.fournisseurs_suppression || false,
            typesLots_lecture                        : req.body.typesLots_lecture || false,
            typesLots_ajout                          : req.body.typesLots_ajout || false,
            typesLots_modification                   : req.body.typesLots_modification || false,
            typesLots_suppression                    : req.body.typesLots_suppression || false,
            lieux_lecture                            : req.body.lieux_lecture || false,
            lieux_ajout                              : req.body.lieux_ajout || false,
            lieux_modification                       : req.body.lieux_modification || false,
            lieux_suppression                        : req.body.lieux_suppression || false,
            lots_lecture                             : req.body.lots_lecture || false,
            lots_ajout                               : req.body.lots_ajout || false,
            lots_modification                        : req.body.lots_modification || false,
            lots_suppression                         : req.body.lots_suppression || false,
            sac_lecture                              : req.body.sac_lecture || false,
            sac_ajout                                : req.body.sac_ajout || false,
            sac_modification                         : req.body.sac_modification || false,
            sac_suppression                          : req.body.sac_suppression || false,
            catalogue_lecture                        : req.body.catalogue_lecture || false,
            catalogue_ajout                          : req.body.catalogue_ajout || false,
            catalogue_modification                   : req.body.catalogue_modification || false,
            catalogue_suppression                    : req.body.catalogue_suppression || false,
            materiel_lecture                         : req.body.materiel_lecture || false,
            materiel_ajout                           : req.body.materiel_ajout || false,
            materiel_modification                    : req.body.materiel_modification || false,
            materiel_suppression                     : req.body.materiel_suppression || false,
            messages_ajout                           : req.body.messages_ajout || false,
            messages_suppression                     : req.body.messages_suppression || false,
            verrouIP                                 : req.body.verrouIP || false,
            commande_lecture                         : req.body.commande_lecture || false,
            commande_ajout                           : req.body.commande_ajout || false,
            commande_etreEnCharge                    : req.body.commande_etreEnCharge || false,
            commande_abandonner                      : req.body.commande_abandonner || false,
            cout_lecture                             : req.body.cout_lecture || false,
            cout_ajout                               : req.body.cout_ajout || false,
            cout_etreEnCharge                        : req.body.cout_etreEnCharge || false,
            cout_supprimer                           : req.body.cout_supprimer || false,
            appli_conf                               : req.body.appli_conf || false,
            reserve_lecture                          : req.body.reserve_lecture || false,
            reserve_ajout                            : req.body.reserve_ajout || false,
            reserve_modification                     : req.body.reserve_modification || false,
            reserve_suppression                      : req.body.reserve_suppression || false,
            reserve_cmdVersReserve                   : req.body.reserve_cmdVersReserve || false,
            reserve_ReserveVersLot                   : req.body.reserve_ReserveVersLot || false,
            vhf_canal_lecture                        : req.body.vhf_canal_lecture || false,
            vhf_canal_ajout                          : req.body.vhf_canal_ajout || false,
            vhf_canal_modification                   : req.body.vhf_canal_modification || false,
            vhf_canal_suppression                    : req.body.vhf_canal_suppression || false,
            vhf_plan_lecture                         : req.body.vhf_plan_lecture || false,
            vhf_plan_ajout                           : req.body.vhf_plan_ajout || false,
            vhf_plan_modification                    : req.body.vhf_plan_modification || false,
            vhf_plan_suppression                     : req.body.vhf_plan_suppression || false,
            vhf_equipement_lecture                   : req.body.vhf_equipement_lecture || false,
            vhf_equipement_ajout                     : req.body.vhf_equipement_ajout || false,
            vhf_equipement_modification              : req.body.vhf_equipement_modification || false,
            vhf_equipement_suppression               : req.body.vhf_equipement_suppression || false,
            vehicules_lecture                        : req.body.vehicules_lecture || false,
            vehicules_ajout                          : req.body.vehicules_ajout || false,
            vehicules_modification                   : req.body.vehicules_modification || false,
            vehicules_suppression                    : req.body.vehicules_suppression || false,
            vehicules_types_lecture                  : req.body.vehicules_types_lecture || false,
            vehicules_types_ajout                    : req.body.vehicules_types_ajout || false,
            vehicules_types_modification             : req.body.vehicules_types_modification || false,
            vehicules_types_suppression              : req.body.vehicules_types_suppression || false,
            maintenance                              : req.body.maintenance || false,
            todolist_perso                           : req.body.todolist_perso || false,
            todolist_lecture                         : req.body.todolist_lecture || false,
            todolist_modification                    : req.body.todolist_modification || false,
            contactMailGroupe                        : req.body.contactMailGroupe || false,
            tenues_lecture                           : req.body.tenues_lecture || false,
            tenues_ajout                             : req.body.tenues_ajout || false,
            tenues_modification                      : req.body.tenues_modification || false,
            tenues_suppression                       : req.body.tenues_suppression || false,
            tenuesCatalogue_lecture                  : req.body.tenuesCatalogue_lecture || false,
            tenuesCatalogue_ajout                    : req.body.tenuesCatalogue_ajout || false,
            tenuesCatalogue_modification             : req.body.tenuesCatalogue_modification || false,
            tenuesCatalogue_suppression              : req.body.tenuesCatalogue_suppression || false,
            cautions_lecture                         : req.body.cautions_lecture || false,
            cautions_ajout                           : req.body.cautions_ajout || false,
            cautions_modification                    : req.body.cautions_modification || false,
            cautions_suppression                     : req.body.cautions_suppression || false,
            etats_lecture                            : req.body.etats_lecture || false,
            etats_ajout                              : req.body.etats_ajout || false,
            etats_modification                       : req.body.etats_modification || false,
            etats_suppression                        : req.body.etats_suppression || false,
            notifications                            : req.body.notifications || false,
            actionsMassives                          : req.body.actionsMassives || false,
            delegation                               : req.body.delegation || false,
            commande_valider_delegate                : req.body.commande_valider_delegate || false,
            desinfections_lecture                    : req.body.desinfections_lecture || false,
            desinfections_ajout                      : req.body.desinfections_ajout || false,
            desinfections_modification               : req.body.desinfections_modification || false,
            desinfections_suppression                : req.body.desinfections_suppression || false,
            typesDesinfections_lecture               : req.body.typesDesinfections_lecture || false,
            typesDesinfections_ajout                 : req.body.typesDesinfections_ajout || false,
            typesDesinfections_modification          : req.body.typesDesinfections_modification || false,
            typesDesinfections_suppression           : req.body.typesDesinfections_suppression || false,
            carburants_lecture                       : req.body.carburants_lecture || false,
            carburants_ajout                         : req.body.carburants_ajout || false,
            carburants_modification                  : req.body.carburants_modification || false,
            carburants_suppression                   : req.body.carburants_suppression || false,
            vehiculeHealthType_lecture               : req.body.vehiculeHealthType_lecture || false,
            vehiculeHealthType_ajout                 : req.body.vehiculeHealthType_ajout || false,
            vehiculeHealthType_modification          : req.body.vehiculeHealthType_modification || false,
            vehiculeHealthType_suppression           : req.body.vehiculeHealthType_suppression || false,
            vehiculeHealth_lecture                   : req.body.vehiculeHealth_lecture || false,
            vehiculeHealth_ajout                     : req.body.vehiculeHealth_ajout || false,
            vehiculeHealth_modification              : req.body.vehiculeHealth_modification || false,
            vehiculeHealth_suppression               : req.body.vehiculeHealth_suppression || false,
            alertesBenevolesLots_lecture             : req.body.alertesBenevolesLots_lecture || false,
            alertesBenevolesLots_affectation         : req.body.alertesBenevolesLots_affectation || false,
            alertesBenevolesLots_affectationTier     : req.body.alertesBenevolesLots_affectationTier || false,
            alertesBenevolesVehicules_lecture        : req.body.alertesBenevolesVehicules_lecture || false,
            alertesBenevolesVehicules_affectation    : req.body.alertesBenevolesVehicules_affectation || false,
            alertesBenevolesVehicules_affectationTier: req.body.alertesBenevolesVehicules_affectationTier || false,
            codeBarre_lecture                        : req.body.codeBarre_lecture || false,
            codeBarre_ajout                          : req.body.codeBarre_ajout || false,
            codeBarre_modification                   : req.body.codeBarre_modification || false,
            codeBarre_suppression                    : req.body.codeBarre_suppression || false,
            consommationLots_lecture                 : req.body.consommationLots_lecture || false,
            consommationLots_affectation             : req.body.consommationLots_affectation || false,
            consommationLots_supression              : req.body.consommationLots_supression || false,
        });
        res.sendStatus(201);
    } catch (error) {
        logger.error(error);
        res.sendStatus(500);
    }
}

exports.updateProfil = async (req, res)=>{
    try {
        let results = await db.query(
            `UPDATE
                PROFILS
            SET
                libelleProfil                             = :libelleProfil,
                LDAP_BINDDN                               = :LDAP_BINDDN,
                descriptifProfil                          = :descriptifProfil,
                connexion_connexion                       = :connexion_connexion,
                annuaire_lecture                          = :annuaire_lecture,
                annuaire_ajout                            = :annuaire_ajout,
                annuaire_modification                     = :annuaire_modification,
                annuaire_mdp                              = :annuaire_mdp,
                annuaire_suppression                      = :annuaire_suppression,
                profils_lecture                           = :profils_lecture,
                profils_ajout                             = :profils_ajout,
                profils_modification                      = :profils_modification,
                profils_suppression                       = :profils_suppression,
                categories_lecture                        = :categories_lecture,
                categories_ajout                          = :categories_ajout,
                categories_modification                   = :categories_modification,
                categories_suppression                    = :categories_suppression,
                fournisseurs_lecture                      = :fournisseurs_lecture,
                fournisseurs_ajout                        = :fournisseurs_ajout,
                fournisseurs_modification                 = :fournisseurs_modification,
                fournisseurs_suppression                  = :fournisseurs_suppression,
                typesLots_lecture                         = :typesLots_lecture,
                typesLots_ajout                           = :typesLots_ajout,
                typesLots_modification                    = :typesLots_modification,
                typesLots_suppression                     = :typesLots_suppression,
                lieux_lecture                             = :lieux_lecture,
                lieux_ajout                               = :lieux_ajout,
                lieux_modification                        = :lieux_modification,
                lieux_suppression                         = :lieux_suppression,
                lots_lecture                              = :lots_lecture,
                lots_ajout                                = :lots_ajout,
                lots_modification                         = :lots_modification,
                lots_suppression                          = :lots_suppression,
                sac_lecture                               = :sac_lecture,
                sac_ajout                                 = :sac_ajout,
                sac_modification                          = :sac_modification,
                sac_suppression                           = :sac_suppression,
                catalogue_lecture                         = :catalogue_lecture,
                catalogue_ajout                           = :catalogue_ajout,
                catalogue_modification                    = :catalogue_modification,
                catalogue_suppression                     = :catalogue_suppression,
                materiel_lecture                          = :materiel_lecture,
                materiel_ajout                            = :materiel_ajout,
                materiel_modification                     = :materiel_modification,
                materiel_suppression                      = :materiel_suppression,
                messages_ajout                            = :messages_ajout,
                messages_suppression                      = :messages_suppression,
                verrouIP                                  = :verrouIP,
                commande_lecture                          = :commande_lecture,
                commande_ajout                            = :commande_ajout,
                commande_etreEnCharge                     = :commande_etreEnCharge,
                commande_abandonner                       = :commande_abandonner,
                cout_lecture                              = :cout_lecture,
                cout_ajout                                = :cout_ajout,
                cout_etreEnCharge                         = :cout_etreEnCharge,
                cout_supprimer                            = :cout_supprimer,
                appli_conf                                = :appli_conf,
                reserve_lecture                           = :reserve_lecture,
                reserve_ajout                             = :reserve_ajout,
                reserve_modification                      = :reserve_modification,
                reserve_suppression                       = :reserve_suppression,
                reserve_cmdVersReserve                    = :reserve_cmdVersReserve,
                reserve_ReserveVersLot                    = :reserve_ReserveVersLot,
                vhf_canal_lecture                         = :vhf_canal_lecture,
                vhf_canal_ajout                           = :vhf_canal_ajout,
                vhf_canal_modification                    = :vhf_canal_modification,
                vhf_canal_suppression                     = :vhf_canal_suppression,
                vhf_plan_lecture                          = :vhf_plan_lecture,
                vhf_plan_ajout                            = :vhf_plan_ajout,
                vhf_plan_modification                     = :vhf_plan_modification,
                vhf_plan_suppression                      = :vhf_plan_suppression,
                vhf_equipement_lecture                    = :vhf_equipement_lecture,
                vhf_equipement_ajout                      = :vhf_equipement_ajout,
                vhf_equipement_modification               = :vhf_equipement_modification,
                vhf_equipement_suppression                = :vhf_equipement_suppression,
                vehicules_lecture                         = :vehicules_lecture,
                vehicules_ajout                           = :vehicules_ajout,
                vehicules_modification                    = :vehicules_modification,
                vehicules_suppression                     = :vehicules_suppression,
                vehicules_types_lecture                   = :vehicules_types_lecture,
                vehicules_types_ajout                     = :vehicules_types_ajout,
                vehicules_types_modification              = :vehicules_types_modification,
                vehicules_types_suppression               = :vehicules_types_suppression,
                maintenance                               = :maintenance,
                todolist_perso                            = :todolist_perso,
                todolist_lecture                          = :todolist_lecture,
                todolist_modification                     = :todolist_modification,
                contactMailGroupe                         = :contactMailGroupe,
                tenues_lecture                            = :tenues_lecture,
                tenues_ajout                              = :tenues_ajout,
                tenues_modification                       = :tenues_modification,
                tenues_suppression                        = :tenues_suppression,
                tenuesCatalogue_lecture                   = :tenuesCatalogue_lecture,
                tenuesCatalogue_ajout                     = :tenuesCatalogue_ajout,
                tenuesCatalogue_modification              = :tenuesCatalogue_modification,
                tenuesCatalogue_suppression               = :tenuesCatalogue_suppression,
                cautions_lecture                          = :cautions_lecture,
                cautions_ajout                            = :cautions_ajout,
                cautions_modification                     = :cautions_modification,
                cautions_suppression                      = :cautions_suppression,
                etats_lecture                             = :etats_lecture,
                etats_ajout                               = :etats_ajout,
                etats_modification                        = :etats_modification,
                etats_suppression                         = :etats_suppression,
                notifications                             = :notifications,
                actionsMassives                           = :actionsMassives,
                delegation                                = :delegation,
                commande_valider_delegate                 = :commande_valider_delegate,
                desinfections_lecture                     = :desinfections_lecture,
                desinfections_ajout                       = :desinfections_ajout,
                desinfections_modification                = :desinfections_modification,
                desinfections_suppression                 = :desinfections_suppression,
                typesDesinfections_lecture                = :typesDesinfections_lecture,
                typesDesinfections_ajout                  = :typesDesinfections_ajout,
                typesDesinfections_modification           = :typesDesinfections_modification,
                typesDesinfections_suppression            = :typesDesinfections_suppression,
                carburants_lecture                        = :carburants_lecture,
                carburants_ajout                          = :carburants_ajout,
                carburants_modification                   = :carburants_modification,
                carburants_suppression                    = :carburants_suppression,
                vehiculeHealthType_lecture                = :vehiculeHealthType_lecture,
                vehiculeHealthType_ajout                  = :vehiculeHealthType_ajout,
                vehiculeHealthType_modification           = :vehiculeHealthType_modification,
                vehiculeHealthType_suppression            = :vehiculeHealthType_suppression,
                vehiculeHealth_lecture                    = :vehiculeHealth_lecture,
                vehiculeHealth_ajout                      = :vehiculeHealth_ajout,
                vehiculeHealth_modification               = :vehiculeHealth_modification,
                vehiculeHealth_suppression                = :vehiculeHealth_suppression,
                alertesBenevolesLots_lecture              = :alertesBenevolesLots_lecture,
                alertesBenevolesLots_affectation          = :alertesBenevolesLots_affectation,
                alertesBenevolesLots_affectationTier      = :alertesBenevolesLots_affectationTier,
                alertesBenevolesVehicules_lecture         = :alertesBenevolesVehicules_lecture,
                alertesBenevolesVehicules_affectation     = :alertesBenevolesVehicules_affectation,
                alertesBenevolesVehicules_affectationTier = :alertesBenevolesVehicules_affectationTier,
                codeBarre_lecture                         = :codeBarre_lecture,
                codeBarre_ajout                           = :codeBarre_ajout,
                codeBarre_modification                    = :codeBarre_modification,
                codeBarre_suppression                     = :codeBarre_suppression,
                consommationLots_lecture                  = :consommationLots_lecture,
                consommationLots_affectation              = :consommationLots_affectation,
                consommationLots_supression               = :consommationLots_supression
            WHERE
                idProfil = :idProfil
            ;`,
        {
            libelleProfil                            : req.body.libelleProfil || null,
            LDAP_BINDDN                              : req.body.LDAP_BINDDN || null,
            descriptifProfil                         : req.body.descriptifProfil || null,
            connexion_connexion                      : req.body.connexion_connexion || false,
            annuaire_lecture                         : req.body.annuaire_lecture || false,
            annuaire_ajout                           : req.body.annuaire_ajout || false,
            annuaire_modification                    : req.body.annuaire_modification || false,
            annuaire_mdp                             : req.body.annuaire_mdp || false,
            annuaire_suppression                     : req.body.annuaire_suppression || false,
            profils_lecture                          : req.body.profils_lecture || false,
            profils_ajout                            : req.body.profils_ajout || false,
            profils_modification                     : req.body.profils_modification || false,
            profils_suppression                      : req.body.profils_suppression || false,
            categories_lecture                       : req.body.categories_lecture || false,
            categories_ajout                         : req.body.categories_ajout || false,
            categories_modification                  : req.body.categories_modification || false,
            categories_suppression                   : req.body.categories_suppression || false,
            fournisseurs_lecture                     : req.body.fournisseurs_lecture || false,
            fournisseurs_ajout                       : req.body.fournisseurs_ajout || false,
            fournisseurs_modification                : req.body.fournisseurs_modification || false,
            fournisseurs_suppression                 : req.body.fournisseurs_suppression || false,
            typesLots_lecture                        : req.body.typesLots_lecture || false,
            typesLots_ajout                          : req.body.typesLots_ajout || false,
            typesLots_modification                   : req.body.typesLots_modification || false,
            typesLots_suppression                    : req.body.typesLots_suppression || false,
            lieux_lecture                            : req.body.lieux_lecture || false,
            lieux_ajout                              : req.body.lieux_ajout || false,
            lieux_modification                       : req.body.lieux_modification || false,
            lieux_suppression                        : req.body.lieux_suppression || false,
            lots_lecture                             : req.body.lots_lecture || false,
            lots_ajout                               : req.body.lots_ajout || false,
            lots_modification                        : req.body.lots_modification || false,
            lots_suppression                         : req.body.lots_suppression || false,
            sac_lecture                              : req.body.sac_lecture || false,
            sac_ajout                                : req.body.sac_ajout || false,
            sac_modification                         : req.body.sac_modification || false,
            sac_suppression                          : req.body.sac_suppression || false,
            catalogue_lecture                        : req.body.catalogue_lecture || false,
            catalogue_ajout                          : req.body.catalogue_ajout || false,
            catalogue_modification                   : req.body.catalogue_modification || false,
            catalogue_suppression                    : req.body.catalogue_suppression || false,
            materiel_lecture                         : req.body.materiel_lecture || false,
            materiel_ajout                           : req.body.materiel_ajout || false,
            materiel_modification                    : req.body.materiel_modification || false,
            materiel_suppression                     : req.body.materiel_suppression || false,
            messages_ajout                           : req.body.messages_ajout || false,
            messages_suppression                     : req.body.messages_suppression || false,
            verrouIP                                 : req.body.verrouIP || false,
            commande_lecture                         : req.body.commande_lecture || false,
            commande_ajout                           : req.body.commande_ajout || false,
            commande_etreEnCharge                    : req.body.commande_etreEnCharge || false,
            commande_abandonner                      : req.body.commande_abandonner || false,
            cout_lecture                             : req.body.cout_lecture || false,
            cout_ajout                               : req.body.cout_ajout || false,
            cout_etreEnCharge                        : req.body.cout_etreEnCharge || false,
            cout_supprimer                           : req.body.cout_supprimer || false,
            appli_conf                               : req.body.appli_conf || false,
            reserve_lecture                          : req.body.reserve_lecture || false,
            reserve_ajout                            : req.body.reserve_ajout || false,
            reserve_modification                     : req.body.reserve_modification || false,
            reserve_suppression                      : req.body.reserve_suppression || false,
            reserve_cmdVersReserve                   : req.body.reserve_cmdVersReserve || false,
            reserve_ReserveVersLot                   : req.body.reserve_ReserveVersLot || false,
            vhf_canal_lecture                        : req.body.vhf_canal_lecture || false,
            vhf_canal_ajout                          : req.body.vhf_canal_ajout || false,
            vhf_canal_modification                   : req.body.vhf_canal_modification || false,
            vhf_canal_suppression                    : req.body.vhf_canal_suppression || false,
            vhf_plan_lecture                         : req.body.vhf_plan_lecture || false,
            vhf_plan_ajout                           : req.body.vhf_plan_ajout || false,
            vhf_plan_modification                    : req.body.vhf_plan_modification || false,
            vhf_plan_suppression                     : req.body.vhf_plan_suppression || false,
            vhf_equipement_lecture                   : req.body.vhf_equipement_lecture || false,
            vhf_equipement_ajout                     : req.body.vhf_equipement_ajout || false,
            vhf_equipement_modification              : req.body.vhf_equipement_modification || false,
            vhf_equipement_suppression               : req.body.vhf_equipement_suppression || false,
            vehicules_lecture                        : req.body.vehicules_lecture || false,
            vehicules_ajout                          : req.body.vehicules_ajout || false,
            vehicules_modification                   : req.body.vehicules_modification || false,
            vehicules_suppression                    : req.body.vehicules_suppression || false,
            vehicules_types_lecture                  : req.body.vehicules_types_lecture || false,
            vehicules_types_ajout                    : req.body.vehicules_types_ajout || false,
            vehicules_types_modification             : req.body.vehicules_types_modification || false,
            vehicules_types_suppression              : req.body.vehicules_types_suppression || false,
            maintenance                              : req.body.maintenance || false,
            todolist_perso                           : req.body.todolist_perso || false,
            todolist_lecture                         : req.body.todolist_lecture || false,
            todolist_modification                    : req.body.todolist_modification || false,
            contactMailGroupe                        : req.body.contactMailGroupe || false,
            tenues_lecture                           : req.body.tenues_lecture || false,
            tenues_ajout                             : req.body.tenues_ajout || false,
            tenues_modification                      : req.body.tenues_modification || false,
            tenues_suppression                       : req.body.tenues_suppression || false,
            tenuesCatalogue_lecture                  : req.body.tenuesCatalogue_lecture || false,
            tenuesCatalogue_ajout                    : req.body.tenuesCatalogue_ajout || false,
            tenuesCatalogue_modification             : req.body.tenuesCatalogue_modification || false,
            tenuesCatalogue_suppression              : req.body.tenuesCatalogue_suppression || false,
            cautions_lecture                         : req.body.cautions_lecture || false,
            cautions_ajout                           : req.body.cautions_ajout || false,
            cautions_modification                    : req.body.cautions_modification || false,
            cautions_suppression                     : req.body.cautions_suppression || false,
            etats_lecture                            : req.body.etats_lecture || false,
            etats_ajout                              : req.body.etats_ajout || false,
            etats_modification                       : req.body.etats_modification || false,
            etats_suppression                        : req.body.etats_suppression || false,
            notifications                            : req.body.notifications || false,
            actionsMassives                          : req.body.actionsMassives || false,
            delegation                               : req.body.delegation || false,
            commande_valider_delegate                : req.body.commande_valider_delegate || false,
            desinfections_lecture                    : req.body.desinfections_lecture || false,
            desinfections_ajout                      : req.body.desinfections_ajout || false,
            desinfections_modification               : req.body.desinfections_modification || false,
            desinfections_suppression                : req.body.desinfections_suppression || false,
            typesDesinfections_lecture               : req.body.typesDesinfections_lecture || false,
            typesDesinfections_ajout                 : req.body.typesDesinfections_ajout || false,
            typesDesinfections_modification          : req.body.typesDesinfections_modification || false,
            typesDesinfections_suppression           : req.body.typesDesinfections_suppression || false,
            carburants_lecture                       : req.body.carburants_lecture || false,
            carburants_ajout                         : req.body.carburants_ajout || false,
            carburants_modification                  : req.body.carburants_modification || false,
            carburants_suppression                   : req.body.carburants_suppression || false,
            vehiculeHealthType_lecture               : req.body.vehiculeHealthType_lecture || false,
            vehiculeHealthType_ajout                 : req.body.vehiculeHealthType_ajout || false,
            vehiculeHealthType_modification          : req.body.vehiculeHealthType_modification || false,
            vehiculeHealthType_suppression           : req.body.vehiculeHealthType_suppression || false,
            vehiculeHealth_lecture                   : req.body.vehiculeHealth_lecture || false,
            vehiculeHealth_ajout                     : req.body.vehiculeHealth_ajout || false,
            vehiculeHealth_modification              : req.body.vehiculeHealth_modification || false,
            vehiculeHealth_suppression               : req.body.vehiculeHealth_suppression || false,
            alertesBenevolesLots_lecture             : req.body.alertesBenevolesLots_lecture || false,
            alertesBenevolesLots_affectation         : req.body.alertesBenevolesLots_affectation || false,
            alertesBenevolesLots_affectationTier     : req.body.alertesBenevolesLots_affectationTier || false,
            alertesBenevolesVehicules_lecture        : req.body.alertesBenevolesVehicules_lecture || false,
            alertesBenevolesVehicules_affectation    : req.body.alertesBenevolesVehicules_affectation || false,
            alertesBenevolesVehicules_affectationTier: req.body.alertesBenevolesVehicules_affectationTier || false,
            codeBarre_lecture                        : req.body.codeBarre_lecture || false,
            codeBarre_ajout                          : req.body.codeBarre_ajout || false,
            codeBarre_modification                   : req.body.codeBarre_modification || false,
            codeBarre_suppression                    : req.body.codeBarre_suppression || false,
            consommationLots_lecture                 : req.body.consommationLots_lecture || false,
            consommationLots_affectation             : req.body.consommationLots_affectation || false,
            consommationLots_supression              : req.body.consommationLots_supression || false,
            idProfil                                 : req.body.idProfil || null
        });

        await fonctionsMetiers.majIndicateursProfil(req.body.idProfil);
        await fonctionsMetiers.majNotificationsProfil(req.body.idProfil)
        await fonctionsMetiers.majValideursPersonne(true);
        await fonctionsMetiers.deconnecterProfil(req.body.idProfil)

        res.sendStatus(201);
    } catch (error) {
        logger.error(error);
        res.sendStatus(500);
    }
}

exports.deleteProfil = async (req, res)=>{
    try {
        const deleteResult = await fonctionsDelete.profilsDelete(req.verifyJWTandProfile.idPersonne , req.body.idProfil);
        if(deleteResult){res.sendStatus(201);}else{res.sendStatus(500);}
    } catch (error) {
        logger.error(error);
        res.sendStatus(500);
    }
}