ALTER TABLE CONFIG ADD LDAP_USER TEXT AFTER LDAP_SSL;
ALTER TABLE CONFIG ADD LDAP_PASSWORD TEXT AFTER LDAP_USER;

INSERT INTO VEHICULES_HEALTH_TYPES SET libelleHealthType = 'Révision', affichageSynthese = 1;
INSERT INTO VEHICULES_HEALTH_TYPES SET libelleHealthType = 'CT', affichageSynthese = 1;
INSERT INTO VEHICULES_HEALTH_TYPES SET libelleHealthType = 'Renouvellement Assurance', affichageSynthese = 1;
