ALTER TABLE PERSONNE_REFERENTE ADD layout VARCHAR(50);
UPDATE PERSONNE_REFERENTE SET layout='fixed';

ALTER TABLE VEHICULES_DESINFECTIONS_TYPES ADD affichageSynthese BOOLEAN;
UPDATE VEHICULES_DESINFECTIONS_TYPES SET affichageSynthese = true;

ALTER TABLE VEHICULES ADD affichageSyntheseDesinfections BOOLEAN;
UPDATE VEHICULES SET affichageSyntheseDesinfections = true;

ALTER TABLE FOURNISSEURS ADD siteWebFournisseur TEXT;
ALTER TABLE FOURNISSEURS CHANGE adresseFournisseur adresseFournisseur TEXT;

UPDATE CONFIG set version = '9.8';