ALTER TABLE CONFIG ADD mailIsSMTP BOOLEAN;
UPDATE CONFIG SET mailIsSMTP = false;

ALTER TABLE CONFIG ADD SMTPhost VARCHAR(50);
ALTER TABLE CONFIG ADD SMTPport INT;
ALTER TABLE CONFIG ADD SMTPssl BOOLEAN;
ALTER TABLE CONFIG ADD SMTPtls BOOLEAN;
ALTER TABLE CONFIG ADD SMTPauth BOOLEAN;
ALTER TABLE CONFIG ADD SMTPuser VARCHAR(100);
ALTER TABLE CONFIG ADD SMTPpwd VARCHAR(100);

UPDATE CONFIG set version = '13.2';