UPDATE LOTS_LOTS set idEtat = 2 WHERE idEtat IS NULL;

ALTER TABLE COMMANDES_MATERIEL ADD quantiteAtransferer INT;
UPDATE COMMANDES_MATERIEL SET quantiteAtransferer=0;

UPDATE CONFIG set version = '3.1';