ALTER TABLE TENUES_AFFECTATION DROP FOREIGN KEY fk_tenuesAff_Catalogue;
ALTER TABLE TENUES_AFFECTATION DROP idCatalogueTenue;

ALTER TABLE TENUES_CATALOGUE DROP libelleCatalogueTenue;
ALTER TABLE TENUES_CATALOGUE DROP tailleCatalogueTenue;

UPDATE CONFIG SET version = '16.0';