ALTER TABLE MATERIEL_CATALOGUE ADD modules_ope BOOLEAN DEFAULT FALSE;
ALTER TABLE MATERIEL_CATALOGUE ADD modules_vehicules BOOLEAN DEFAULT FALSE;
ALTER TABLE MATERIEL_CATALOGUE ADD modules_tenues BOOLEAN DEFAULT FALSE;
ALTER TABLE MATERIEL_CATALOGUE ADD modules_vhf BOOLEAN DEFAULT FALSE;

ALTER TABLE MATERIEL_CATALOGUE ADD peremptionAnticipationVehicule INT DEFAULT NULL AFTER peremptionAnticipationRes;
ALTER TABLE MATERIEL_CATALOGUE ADD peremptionAnticipationTenues INT DEFAULT NULL AFTER peremptionAnticipationVehicule;
ALTER TABLE MATERIEL_CATALOGUE ADD peremptionAnticipationVHF INT DEFAULT NULL AFTER peremptionAnticipationTenues;

UPDATE MATERIEL_CATALOGUE SET modules_ope = true;

CREATE OR REPLACE VIEW VIEW_MATERIEL_CATALOGUE_OPE AS
	SELECT
		*
	FROM
		MATERIEL_CATALOGUE
	WHERE
        modules_ope = true
;

CREATE OR REPLACE VIEW VIEW_MATERIEL_CATALOGUE_VEHICULES AS
	SELECT
		*
	FROM
		MATERIEL_CATALOGUE
	WHERE
        modules_vehicules = true
;

CREATE OR REPLACE VIEW VIEW_MATERIEL_CATALOGUE_TENUES AS
	SELECT
		*
	FROM
		MATERIEL_CATALOGUE
	WHERE
        modules_tenues = true
;

CREATE OR REPLACE VIEW VIEW_MATERIEL_CATALOGUE_VHF AS
	SELECT
		*
	FROM
		MATERIEL_CATALOGUE
	WHERE
        modules_vhf = true
;

ALTER TABLE TENUES_CATALOGUE ADD idMaterielCatalogue INT DEFAULT NULL AFTER idCatalogueTenue;
ALTER TABLE TENUES_CATALOGUE ADD CONSTRAINT fk_tenuesCat_catalogue FOREIGN KEY(idMaterielCatalogue) REFERENCES MATERIEL_CATALOGUE(idMaterielCatalogue);
ALTER TABLE TENUES_CATALOGUE ADD UNIQUE(idMaterielCatalogue);
ALTER TABLE TENUES_AFFECTATION ADD idMaterielCatalogue INT DEFAULT NULL AFTER idTenue;
ALTER TABLE TENUES_AFFECTATION ADD CONSTRAINT fk_tenuesAffect_catalogue FOREIGN KEY(idMaterielCatalogue) REFERENCES MATERIEL_CATALOGUE(idMaterielCatalogue);

ALTER TABLE MATERIEL_CATALOGUE DROP INDEX libelleMateriel;
ALTER TABLE TENUES_CATALOGUE DROP serigraphieCatalogueTenue;