ALTER TABLE MATERIEL_ELEMENT ADD numeroSerie TEXT NULL AFTER peremptionNotification;
ALTER TABLE RESERVES_MATERIEL ADD numeroSerie TEXT NULL AFTER peremptionNotificationReserve;

ALTER TABLE MATERIEL_CATALOGUE ADD disponibleBenevolesConso BOOLEAN DEFAULT false;

ALTER TABLE TENUES_AFFECTATION ADD mailPersonneNonGPM VARCHAR(100) DEFAULT NULL AFTER personneNonGPM;
ALTER TABLE TENUES_AFFECTATION ADD notifPersonne BOOLEAN DEFAULT FALSE AFTER mailPersonneNonGPM;
ALTER TABLE CAUTIONS ADD mailPersonneNonGPM VARCHAR(100) DEFAULT NULL AFTER personneNonGPM;

UPDATE CONFIG SET version = '15.1';