ALTER TABLE CONFIG DROP SMTPhost;
ALTER TABLE CONFIG DROP SMTPport;
ALTER TABLE CONFIG DROP SMTPssl;
ALTER TABLE CONFIG DROP SMTPtls;
ALTER TABLE CONFIG DROP SMTPauth;
ALTER TABLE CONFIG DROP SMTPuser;
ALTER TABLE CONFIG DROP SMTPpwd;
ALTER TABLE CONFIG DROP mailIsSMTP;
ALTER TABLE CONFIG DROP LDAP_DOMAIN;
ALTER TABLE CONFIG DROP LDAP_BASEDN;
ALTER TABLE CONFIG DROP LDAP_ISWINAD;
ALTER TABLE CONFIG DROP LDAP_SSL;
ALTER TABLE CONFIG DROP LDAP_USER;
ALTER TABLE CONFIG DROP LDAP_PASSWORD;
ALTER TABLE CONFIG DROP reCaptcha_enable;
ALTER TABLE CONFIG DROP reCaptcha_siteKey;
ALTER TABLE CONFIG DROP reCaptcha_secretKey;
ALTER TABLE CONFIG DROP reCaptcha_scoreMin;
ALTER TABLE CONFIG DROP verrouillage_ip_occurances;
ALTER TABLE CONFIG DROP verrouillage_ip_temps;
ALTER TABLE CONFIG DROP selPre;
ALTER TABLE CONFIG DROP selPost;
ALTER TABLE CONFIG DROP confirmationSuppression;
ALTER TABLE CONFIG DROP logouttemp;
ALTER TABLE CONFIG DROP sitecolor;

CREATE TABLE JWT_SESSIONS(
	idSession       INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	idPersonne      INT,
	createdDateTime DATETIME,
	jwtToken        TEXT,
	jwtRefreshToken TEXT,
	tokenValidity   DATETIME,
	refreshValidity DATETIME,
	CONSTRAINT fk_sessions_personne
		FOREIGN KEY (idPersonne)
		REFERENCES PERSONNE_REFERENTE(idPersonne)
);

CREATE TABLE JWT_SESSIONS_BLACKLIST(
	idBlackList     INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	blockedDateTime DATETIME,
	jwtToken        TEXT
);

CREATE TABLE MAIL_QUEUE(
	idMailQueue  INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	typeMail     VARCHAR(20),
	idObject     INT,
	idSecondaire INT,
	lastTry      DATETIME,
	retryCounter INT DEFAULT 0
);

UPDATE CONFIG SET version = '15.0';